### ISSUE TITLE
Arduino mini/nano

### ISSUE THREAD

**Issue by vasyl91** [filippofilip95/bluetooth-led-controller#1]
Will that work with Arduino mini/small? I would need to reduce size of this module.

**Comment by filippofilip95** [comment]
I realised that is also missing builded apk file. Let me know if you need it.

**Comment by vasyl91** [comment]
Thank you for your reply! It would be nice if u could upload the APK file ;)

**Comment by filippofilip95** [comment]
Just added :) b71cbf95eb57f978b9ab576e7520ad4d88c85bc6

I'll make docs for this project but not sure when :)

**Comment by vasyl91** [comment]
Ok, thanks! ;)

**Comment by vasyl91** [comment]
Hey, sorry to bother you again, but is there any chance you'll provide a brightness control or at least give some clues how to do that? Thanks in advance ;)

**Comment by filippofilip95** [comment]
Brightness control is handled in app by [react-native-color-picker](https://github.com/instea/react-native-color-picker#readme) package.
If i remember correctly it worked when i've tried it for the last time :)
